[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filepath = "0.1.2"
clicolors-control = "1.0.1"
enum-as-inner = "0.5.0"
regex = "1.5.6"
serde-value = "0.7.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
chrono = "0.4.19"
hex = "0.4.3"


[profile.dev]
opt-level = 1