#![feature(downcast_unchecked)]
#![feature(dec2flt)]
#![feature(core_intrinsics)]
#![feature(test)]
#![feature(arc_unwrap_or_clone)]
#![feature(mutex_unlock)]
#![feature(get_mut_unchecked)]
#![feature(fn_traits)]
#![feature(cell_leak)]
#![feature(ptr_as_uninit)]
#![feature(once_cell)]
#![feature(hash_set_entry)]
#![feature(try_trait_v2)]
#![feature(is_some_and)]
#![feature(path_file_prefix)]
#![feature(unsized_fn_params)]
#![feature(pointer_byte_offsets)]
#![feature(sync_unsafe_cell)]
#![feature(ptr_internals)]
#![feature(let_chains)]
#![feature(allocator_api)]
#![feature(try_reserve_kind)]
#![feature(new_uninit)]
#![feature(unchecked_math)]
#![feature(const_trait_impl)]
#![feature(pointer_is_aligned)]
#![feature(layout_for_ptr)]
#![feature(ptr_to_from_bits)]
#![feature(ptr_metadata)]
#![feature(const_align_of_val_raw)]
#![feature(const_size_of_val_raw)]
#![feature(const_mut_refs)]
#![feature(arbitrary_enum_discriminant)]

pub mod leblanc;
pub mod playground;

extern crate alloc;
extern crate core;